// app/layout.tsx ou globals/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import MenuWrapper from "@/components/ui/MenuWrapper";
import { UserProvider } from "@/contexts/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth bg-[#f8f8f5] text-gray-800 dark:bg-[#111418] dark:text-gray-200 transition-colors duration-300`}
      >
        <UserProvider>
          {children}
          <Toaster />
          <MenuWrapper />
        </UserProvider>
      </body>
    </html>
  );
}
